spring:
  datasource:
    password: cropy
    url: jdbc:mysql://localhost:3306/imap
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect